FROM flink:1.14.4-scala_2.12-java11

LABEL author="Mario Vicente Albertos"
LABEL maintainer="mariov22 <mario.vicente.albertos@alumnos.upm.es>"
LABEL description="Docker image for kafka producer microservice."

ADD traffic-rate-1.1.jar /opt/flink/usrlib/traffic-rate.jar